### ISSUE TITLE
Assemble gradle task failing

### ISSUE THREAD

**Issue by MrMineO5** [sourceplusplus/live-platform#430]
When running `gradle -p platform assemble`, the :protocol:kaptKotlinJvm task fails with multiple error messages relating to vertx code generation, such as the following:
```
Could not generate model for spp.protocol.service.LiveInstrumentService#addLiveInstrument(spp.protocol.instrument.LiveInstrument): type spp.protocol.instrument.LiveInstrument is not legal for use for a parameter in proxy
```

This issue does not appear when running the assemble or build tasks with `gradle -p protocol assemble`, during which it runs many more gradle tasks before the kaptKotlinJvm one.

**Comment by BFergerson** [comment]
This is an annoying issue I'm aware of. I don't think I realized "it runs many more gradle tasks before the kaptKotlinJvm one" before though so that might be the fix it finally needs.

In the meantime, delete the `protocol/build` directory and you should be good to go.

**Comment by BFergerson** [comment]
Looks like #431 doesn't fully solve this.
