### ISSUE TITLE
Could not resolve org.nodejs:node:16.15.0

### ISSUE THREAD

**Issue by MrMineO5** [sourceplusplus/live-platform#434]
Gradle is unable to resolve the org.nodejs:node:16.15.0 dependency for :interfaces:booster-ui:nodeSetup

**Comment by BFergerson** [comment]
Can you try again? I was upgrading the `pkg.sourceplus.plus` server and I may have caused that issue. I know I caused a similar issue just now in the actions workflow. If it happens again please include the error message.

**Comment by BFergerson** [comment]
Also, I'm pretty sure that should be a one-time step. How long does `./gradlew -p platform assembleUp` take to run? I assume that's the command you're running to run into this issue.

**Comment by MrMineO5** [comment]
It is a one-time step, but I was setting up the project on a different computer. It does indeed work now.
