### ISSUE TITLE
Support multiple projects simultaneously

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/live-platform#475]
Seems to work a bit but it should be verified that the two IDEs don't share anything they shouldn't share

**Comment by MrMineO5** [comment]
Is this issue in reference to using multiple different Jetbrains IDEs, or multiple projects open in the same IDE?

**Comment by BFergerson** [comment]
Multiple JetBrains IDEs. Guessing you ran into this issue?

**Comment by MrMineO5** [comment]
I haven't tried multiple Jetbrains IDEs, since I mostly use IntelliJ, but I often have multiple projects open in IntelliJ, which doesn't work.

**Comment by BFergerson** [comment]
By multiple projects, do you mean multiple modules? I don't think IntelliJ supports multiple projects per IDE.

**Comment by MrMineO5** [comment]
You can have multiple windows of the same IDE open with different projects

**Comment by BFergerson** [comment]
Ah, yeah okay. Yeah, this issue covers that too. All the new code I've been adding supports multiple projects but there is old code that doesn't. I'll look into closing this issue.
