### ISSUE TITLE
Null live variable support

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/live-platform#549]

**Comment by MrMineO5** [comment]
What about languages with multiple nulls, such as javascript which has null and undefined. It may be important to know which one it is for debugging.qq

**Comment by BFergerson** [comment]
I added another live variable annotation `@null`. It's unnecessary for JVM implementations but I thought it might be useful for JavaScript.

It's not being passed to the IDE yet but none of the live variable annotations are yet. I'll make another issue to start passing those through. Then it would just be a change on the IDE plugin to support JavaScript's different null types.
